name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 (latest)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to v2 (latest)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t jermgaming/portfolio:latest .
          docker push jermgaming/portfolio:latest